wechat:
  appId: wx4d1f59cc41e1c601
  appSecret: 5cb8a75bd031b350957fa7e7d5e357eb
  token: emonnote

#spring:
#  cache:
#    type: redis
#    cache-names: redisCache
#  redis:
#    database: 0
#    host: 172.19.219.184
#    port: 6379
#    timeout: 0
#    password: ss541018
#    sentinel:
#      master: mymaster
#      nodes: 172.19.219.184:26379,172.19.219.184:26389,172.19.219.184:26399

ftp:
  servers[0]:
    alias: default
    host: 192.168.1.56
    port: 21
    username: ftp
    password: ftp123
    passiveMode: true
    accessUrlPrefixes: http://zygfile.zhaoshengbao.org