wechat:
  appId: wxf46908d1b94ffc6c
  appSecret: 26c765de9bbe93f5b131856bd107da25
  token: emonnote

# 项目通用配置
common:
  uploadUrl: https://img.tamizoo.cn/upload
  orderTimeOut: 15
  wxOderTimeDiff: 5

#spring:
# cache:
#   type: redis
#   cache-names: redisCache
# redis:
#   database: 0
#   host: 172.19.219.184
#   port: 6379
#   timeout: 0
#   password: ss541018
#   sentinel:
#     master: mymaster
#     nodes: 172.19.219.184:26379,172.19.219.184:26389,172.19.219.184:26399

ftp:
  servers[0]:
    alias: default
    host: 10.0.0.116
    port: 21
    username: ftp
    password: ftp123
    accessUrlPrefixes: http://10.0.0.116
  servers[1]:
    alias: localUser
    host: 192.168.1.116
    port: 21
    username: ftpuser
    password: ftpuser123
    accessUrlPrefixes: http://192.168.1.116
  servers[2]:
    alias: virtualUser
    host: 192.168.1.116
    port: 21
    username: ftp
    password: ftp123
    accessUrlPrefixes: http://192.168.1.116